Update workflow for consistency

diff --git a/.github/workflows/run-tests-linux.yml b/.github/workflows/run-tests-linux.yml
--- a/.github/workflows/run-tests-linux.yml
+++ b/.github/workflows/run-tests-linux.yml
@@ -11,10 +11,7 @@ jobs:
     strategy:
       matrix:
         compiler: [gcc, clang, tcc]
-        include:
-          - compiler: tcc
-            install: true
-
+    
     steps:
     - name: Checkout code with submodules
       uses: actions/checkout@v3
@@ -24,57 +21,27 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
     
     - name: Install TCC
-      if: matrix.install
+      if: matrix.compiler == 'tcc'
       run: |
         sudo apt-get update
         sudo apt-get install -y tcc
-
-    - name: Test arena tests
-      working-directory: ./tests
-      run: |
-        ${{ matrix.compiler }} arena-tests.c -o arena-tests
-        ./arena-tests
-        if [ $? -ne 0 ]; then
-          echo "arena-tests failed with ${{ matrix.compiler }}"
-          exit 1
-        fi
     
-    - name: Test file system tests
+    - name: Run tests
       working-directory: ./tests
       run: |
-        ${{ matrix.compiler }} file-system-tests.c -o file-system-tests
-        ./file-system-tests
-        if [ $? -ne 0 ]; then
-          echo "file-system-tests failed with ${{ matrix.compiler }}"
-          exit 1
-        fi
-    
-    - name: Test ini parser tests
-      working-directory: ./tests
-      run: |
-        ${{ matrix.compiler }} ini-parser-tests.c -o ini-parser-tests -lm
-        ./ini-parser-tests
-        if [ $? -ne 0 ]; then
-          echo "ini-parser-tests failed with ${{ matrix.compiler }}"
-          exit 1
-        fi
-
-    - name: Test string tests
-      working-directory: ./tests
-      run: |
-        ${{ matrix.compiler }} string-tests.c -o string-tests
-        ./string-tests
-        if [ $? -ne 0 ]; then
-          echo "string-tests failed with ${{ matrix.compiler }}"
-          exit 1
-        fi
-    
-    - name: Test vector tests
-      working-directory: ./tests
-      run: |
-        ${{ matrix.compiler }} vector-tests.c -o vector-tests
-        ./vector-tests
-        if [ $? -ne 0 ]; then
-          echo "vector-tests failed with ${{ matrix.compiler }}"
-          exit 1
-        fi
+        for test in arena-tests file-system-tests ini-parser-tests string-tests vector-tests; do
+          echo "Running $test with ${{ matrix.compiler }}..."
+          
+          # Special case for ini-parser-tests which needs -lm
+          if [ "$test" == "ini-parser-tests" ]; then
+            ${{ matrix.compiler }} $test.c -o $test -lm
+          else
+            ${{ matrix.compiler }} $test.c -o $test
+          fi
+          
+          ./$test
+          if [ $? -ne 0 ]; then
+            echo "$test failed with ${{ matrix.compiler }}"
+            exit 1
+          fi
+        done
